import { MenuItem } from './types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'cappuccino',
    name: 'Cappuccino',
    nameAr: 'كابوتشينو',
    category: 'cafes',
    price: 450,
    description: 'Espresso intense, mousse de lait veloutée et art éphémère.',
    descriptionAr: 'إسبريسو غني ورغوة حليب مخملية بنقش فني يدوي.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCTZFvLeGj3H5VawcTa3i87oUS7nbFuzWb3Hd1HtC3GDlNZhSi8QE37fjn9g2s_kANoDI3sOl54gKzMl4NiOPHbJ0_TKmNZYL6oU7LmuQkSFzXJI4xyKILXiuOU7J5iPMu9YuI4YJht7ojn9IaVPmyWj24JKQtxL6MQoP0uaoRAV-xIPfQTSlyacjns19m-T2kBNQD0UYUHSZeMuBTGQpe03KYjacQwbN3SpXd17oy1GrWXZ7ULhjGB-sqiDq-T2Q7OfGR8nkPpOW8',
    customizable: true
  },
  {
    id: 'chocolat-chaud',
    name: 'Chocolat Chaud',
    nameAr: 'شوكولاتة ساخنة',
    category: 'cafes',
    price: 550,
    description: 'Chocolat noir fondu, crème onctueuse et une touche de vanille Bourbon.',
    descriptionAr: 'شوكولاتة داكنة ذائبة، كريمة كثيفة غنية ومسة الفانيليا بوربون الفاخرة.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDVti0s8h2VFnke8wNwEVgiPD8HRRt5Co9CalZmHQ9WHX6vEAhV7--0a0SmvMiAM55Htz9SbyghqIQKQ0WXaH7uzl_6qlhSCRDdEBhJwz8oZGQERy96HgHI1lJXBn0_pqHVGcO7lUgXrbmk7nIqJH71R2EdrcbCryXCiYrAZw2uJiURcawIKINWfyj2Gw_5RQ17DXg62I_LEWQ7j4lIRupZZ4j4dFsm4R5ZVfipfGAhqq6z2q-e3GNLiYaRTFGOaQjzuC5_t2v7nq0',
    tag: 'SIGNATURE',
    customizable: true
  },
  {
    id: 'espresso',
    name: 'Espresso Ristretto',
    nameAr: 'إسبريسو ريستريتو',
    category: 'cafes',
    price: 250,
    description: 'Café court et intense aux notes chocolatées et florales.',
    descriptionAr: 'قهوة مركزة وقصيرة مع إيحاءات الشوكولاتة والأزهار العطرة.',
    customizable: true
  },
  {
    id: 'cafe-noisette',
    name: 'Café Noisette',
    nameAr: 'كافيه نextensions',
    category: 'cafes',
    price: 300,
    description: 'Espresso serré surmonté d’une délicate larme de mousse de lait.',
    descriptionAr: 'إسبريسو كلاسيكي مركز مع لمسة رقيقة من رغوة الحليب.',
    customizable: true
  },
  {
    id: 'thes-exception',
    name: "Thés d'Exception",
    nameAr: 'شاهي الفخامة',
    category: 'cafes',
    price: 400,
    description: 'Sélection de thés verts de Kyoto, de thés noirs de Ceylan et d’infusions bio.',
    descriptionAr: 'مجموعة مختارة من الشاي الأخضر من كيوتو وشاي سيلان الأسود العضوي.',
    customizable: true
  },
  {
    id: 'coupe-fruits',
    name: 'Coupe de Fruits',
    nameAr: 'كوب سلطة فواكه',
    category: 'boissons',
    price: 650,
    description: 'Assortiment de fruits de saison locaux, menthe fraîche et filet de sirop de fleur d’oranger d’Alger.',
    descriptionAr: 'فواكه موسمية محلية طازجة، نعناع بري عطر، وقطرات من ماء زهر البرتقال العاصمي.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB-1zc_YtDKmWFOHFO0ZsBprn570t0JvIofswusHinY99TwLXHTOLz_YxAdDX-4gW2lvX2SVTrzDfHk4BRFfzreyT13Fbg-tiUQI_F5TAK8My17DxsSmEzgt31vSGMD-lUQiq2LFuCxDe3SCDp0u4UmzwGVVr3K41wH0qDqLrK3hHr1U7Gr3osT2DetdHxphGoa-VOshiM4Fukp_Te7XHbL8pRnUyqCuPmwIHsOnj1cwtJwiNjaj4fXqd4Qjedm36qI3nQ4cA3RqrU',
    tag: 'FAVORI',
    customizable: false
  },
  {
    id: 'jus-orange',
    name: "Jus d'Orange Pressé",
    nameAr: 'عصير برتقال طبيعي',
    category: 'boissons',
    price: 400,
    description: 'Oranges d’Algérie fraîchement pressées à la commande pour faire le plein de vitamines.',
    descriptionAr: 'عصير برتقال جزائري طازج يُعصر عند الطلب غني بالفيتامينات والنكهة.',
    customizable: false
  },
  {
    id: 'limonade',
    name: 'Limonade Maison au Basilic',
    nameAr: 'ليموناضة منزلية بالريحان',
    category: 'boissons',
    price: 350,
    description: 'Citrons pressés, sucre de canne roux, infusion de basilic frais et eau filtrée pétillante.',
    descriptionAr: 'عصير الليمون المنعش، سكر القصب الخام، ريحان مفروم ناعم ومياه فوارة نقية.',
    customizable: false
  },
  {
    id: 'mojito-fraise',
    name: 'Mojito Fraise Sauvage',
    nameAr: 'موهيتو الفراولة البرية',
    category: 'boissons',
    price: 500,
    description: 'Purée de fraises, menthe fraîche pilée, tranches de lime et eau gazeuse rafraîchissante.',
    descriptionAr: 'مزيج الفراولة الطازجة، أوراق النعناع المهروسة، شرائح الليمون الأخضر والمياه الفوارة.',
    customizable: false
  },
  {
    id: 'cheesecake',
    name: 'Cheesecake Framboise',
    nameAr: 'تشيزكيك الفراولة والFramboise',
    category: 'patisseries',
    price: 750,
    description: 'Sablé craquant croustillant, fromage frais onctueux et coulis de framboises sauvages.',
    descriptionAr: 'قاعدة البسكويت المقرمش مع جبنة كريمية فاخرة مغطاة بصلصة الفراولة والFramboise البرية.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAWM1xMSoocfAF_baLxZk4gE4YNehWwOMqqPXNLGcC9Up7JMuknbUiMngR1h7qboOsyDcV_esz679fv0m75tjCic8DpTqyKmgP33MGwHrbI5ZD8HrqQ-TqAIXMl1U1orxFrzDnGqKnaWLGF04DFb-e0WdbHRkoh5M2i2umeBw2-Cyg8YaXXYL6GAKNWe1QTs5PHBR_GRjOVG5zvAegy08KJp5NiYs_ktfe_ctGPK7EexA21oMV2YR51WNjDXGweothChRd3kGhuEOI',
    tag: 'SIGNATURE',
    customizable: false
  },
  {
    id: 'oriental',
    name: 'Assortiment Oriental Prestige',
    nameAr: 'تشكيلة الحلويات الشرقية الفاخرة',
    category: 'patisseries',
    price: 850,
    description: 'Duo de baklavas croustillantes, makrouds artisanaux au miel pur d’Algérie et brisures de pistaches.',
    descriptionAr: 'بقلاوة مقرمشة، مقروط تقليدي بالسميد المذهب والعسل الجزائري الصافي، مرشوش بالفستق الحلبي.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAZXzpMK9pGUj757ys-ASmoE_q-KTSSJjaE2zTN0CkW1Lq3cD3u_oW5_tNyeWVg9etEhu7V4o6H058H5bU9mRS0Ieatbjxt7GWAR33h6vlac0DxBIN7GhzQYR3QWRG8pTpbC3BfO-Oe3kkEUd_rCuFGYYsBkSindq8sVogfShU7eWzYGb_hoEoPWjWwObEVj4H2-DnswMVcZHNHrmM8xNrRsEDt_0-OdQrD-atoYg5XohvDsjAIVuRq6-sWVGqQsaeGHuPUkipM2pc',
    customizable: false
  },
  {
    id: 'salade-avocat',
    name: 'Salade Avocat & Mozzarella',
    nameAr: 'سلطة الأفوكادو والموزاريلا',
    category: 'salades',
    price: 950,
    description: 'Mozzarella di bufala italienne, avocats crémeux, tomates cerises juteuses, basilic frais et filet d’huile d’olive extra vierge.',
    descriptionAr: 'جبن موزاريلا بوفالا الفاخر، قطع الأفوكادو الكريمية، طماطم كرزية طازجة، ريحان عطري وزيت زيتون بكر ممتاز.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDKgeL9C5PirwUhoR3Rx1O3L8RkT9SrsmXJaMMyqz4YGLwJiQlXPVL3E4DPle9cJI8dPi9hNb7_ZOvb1xXaoSbaxeOOPrv6bbevnEwcQIulJ9I9KXo8DmCw0zYOEOoBcj5c97SrybSquyHLTus1SXgsuZzvw3Zjpchb1bAMti50eMswRg7V9-hD3WpI0TiMygRswurSu1gwo0S39gOxTCLZ7xXyYwzkYVpEqH_0lJG9msO-3ABqlTF8aE2dBOyqEQ8nuqKUSwQavIw',
    tag: 'SIGNATURE',
    customizable: false
  },
  {
    id: 'cesar-classique',
    name: 'Salade César Classique',
    nameAr: 'سلطة سيزر الكلاسيكية',
    category: 'salades',
    price: 850,
    description: 'Romaine croquante, filet de poulet doré, parmesan affiné, croûtons dorés à l’ail et sauce césar crémeuse maison.',
    descriptionAr: 'خس روماني مقرمش، صدر دجاج مشوي، جبن بارميزان رقيق، خبز محمص بالثوم، وصلصة سيزر السرية.',
    customizable: false
  },
  {
    id: 'toast-avocat',
    name: 'Toast Avocat & Œuf Poché',
    nameAr: 'توست الأفوكادو مع البيض المخفوق',
    category: 'salades',
    price: 750,
    description: 'Pain au levain toasté, écrasé d’avocat citronné aux graines de chia fleur de sel et œuf poché coulant.',
    descriptionAr: 'خبز ريفي محمص مغطى بهريس الأفوكادو العضوي، بيض مسلوق سائل، مع مسبعة بذور الشيا وزيت الزيتون.',
    customizable: false
  }
];

export const HIGHLIGHTS_IDS = ['salade-avocat', 'chocolat-chaud', 'cheesecake', 'coupe-fruits', 'cappuccino', 'oriental'];

export const DICTIONARY = {
  fr: {
    title: 'Happy Space',
    subtitle: 'Salon de thé · Café · Pâtisserie · Since 2020',
    address: '15 RUE DIDOUCHE MOURAD, ALGER CENTRE',
    viewMenu: 'VOIR LE MENU →',
    findUs: 'NOUS TROUVER',
    home: 'Home',
    menu: 'Menu',
    visitUs: 'Visit Us',
    quote: '"Un endroit magique. On s\'y habitue rapidement."',
    aboutTitle: 'Notre Histoire',
    aboutText: 'Né au cœur d\'Alger Centre sur l\'emblématique Rue Didouche Mourad, Happy Space est un hommage à l\'art de vivre. Entre héritage classique et touches contemporaines, nous cultivons le silence, la saveur et la sérénité. Un refuge pour les âmes en quête d\'excellence artisanale.',
    highlightsTitle: 'SÉLECTIONS DE LA MAISON',
    atmosphereTitle: 'ATMOSPHÈRE',
    scrollHint: 'Défilez →',
    interior: 'Intérieur',
    ourCoffee: 'Nos Cafés',
    ourPâtisserie: 'Pâtisseries',
    whyTitle: 'Pourquoi nous choisir ?',
    reasons: [
      { text: 'Jazz du matin pour un éveil en douceur', icon: 'music' },
      { text: 'Pâtisseries au niveau français contemporain', icon: 'cake' },
      { text: 'Cafés de spécialité sourcés éthiquement', icon: 'coffee' },
      { text: 'Un cadre historique colonial magnifiquement préservé', icon: 'landmark' },
      { text: 'Service attentionné et profondément chaleureux', icon: 'heart' }
    ],
    comeVisitUs: 'Venez nous voir',
    openingHours: 'Tous les jours : 08:00 — 22:00',
    phoneNumber: '+213 (0) 21 00 00 00',
    bookingBtn: 'RÉSERVER UNE TABLE',
    mapTitle: 'Carte Interactive',
    exploreAlgiers: 'EXPLORE CENTER ALGIERS',
    allRightsReserved: 'Slow living in every sip.',
    backToHome: '← Accueil',
    categories: {
      cafes: 'CAFÉS & THÉS',
      boissons: 'BOISSONS',
      patisseries: 'PÂTISSERIES',
      salades: 'SALADES'
    },
    filterAll: 'Tous les produits',
    searchPlaceholder: 'Rechercher un délice...',
    priceDZD: 'DA',
    cartTitle: 'Votre Panier',
    cartEmpty: 'Votre panier est vide. Laissez-vous tenter par nos spécialités.',
    addToCart: 'Ajouter au panier',
    customize: 'Personnaliser votre boisson',
    milkOption: 'Choix du Lait',
    sweetnessOption: 'Degré de Sucre',
    extraShotOption: 'Espresso Supplémentaire (+100 DA)',
    notesPlaceholder: 'Remques particulières (ex: sans caféine, à emporter)...',
    totalPrice: 'Prix Total',
    total: 'Total',
    orderNow: 'Passer la commande',
    bookingTitle: 'Réserver une Table',
    fullName: 'Nom Complet',
    phoneNumberLabel: 'Numéro de Téléphone',
    emailLabel: 'Adresse E-mail (Optionnel)',
    guestsNumber: 'Nombre d\'invités',
    bookingDate: 'Date',
    bookingTime: 'Heure Souhaitée',
    seatingArea: 'Section de la Salle',
    seatingOptions: {
      salle_principale: 'Salle Principale (Atmosphère animée)',
      jazz_corner: 'Coin Jazz (Près de la musique live)',
      window_view: 'Vue sur la Fenêtre (Rue Didouche)',
      terrace: 'Petite Terrasse extérieure'
    },
    specialRequests: 'Demandes spéciales',
    confirmBooking: 'Confirmer la Réservation',
    bookingSuccess: 'Félicitations! Votre réservation a été enregistrée avec succès.',
    bookingUnderReview: 'Notre équipe vous contactera sous peu pour confirmation.',
    cartSuccess: 'Commande envoyée avec succès au barman de la table!',
    cartTableNum: 'Numéro de Table',
    myBookings: 'Mes Réservations',
    noReservations: 'Aucune réservation trouvée dans vos sessions.',
    optionsLabelWhole: 'Lait entier (Standard)',
    optionsLabelOat: 'Lait d\'Avoine (+80 DA)',
    optionsLabelAlmond: 'Lait d\'Amande (+80 DA)',
    sweetnessNormal: 'Sucre Normal',
    sweetnessLess: 'Moins de Sucre',
    sweetnessNone: 'Sans Sucre',
    allPricesExplanation: 'Tous nos prix sont en Dinar Algérien (DZD/DA).',
    servingTypeTable: 'Service à Table',
    servingTypeTakeaway: 'À Emporter',
    tablePlaceholder: 'Ex: Table N° 4',
    servingTypeSelect: 'Mode de Service',
    viewMyBookings: 'Voir mes réservations',
    close: 'Fermer',
    jazzLiveAt: 'Sessions Jazz en Live tous les soirs à partir de 19h',
    cancel: 'Annuler',
    confirmedStatus: 'Confirmé',
    orderHistory: 'Historique des Commandes',
    orderEmpty: 'Aucune commande passée pour le moment.',
    orderPlaced: 'Commande n°'
  },
  ar: {
    title: 'هابي سبيس',
    subtitle: 'صالون شاي · مقهى · حلويات · منذ 2020',
    address: '15 شارع ديدوش مراد، وسط الجزائر العاصمة',
    viewMenu: 'عرض قائمة الطعام ←',
    findUs: 'موقعنا والاتصال',
    home: 'الرئيسية',
    menu: 'القائمة',
    visitUs: 'تفضل بزيارتنا',
    quote: '"مكان ساحر وسريالي. تعتاد عليه بسرعة فائقة."',
    aboutTitle: 'قصتنا وهويتنا',
    aboutText: 'نشأ هابي سبيس في قلب وسط الجزائر العاصمة بشارع ديدوش مراد التاريخي، ليكون بمثابة تكريم لفن العيش والهدوء. نمزج بين التراث الجزائري العريق والكلاسيكي مع لمسات عصرية فاخرة، لنصنع ملاذاً للباحثين عن جودة القهوة اليدوية والحلويات المتقنة.',
    highlightsTitle: 'مختارات البيت المتميزة',
    atmosphereTitle: 'الأجواء الساحرة لدينا',
    scrollHint: 'اسحب لرؤية المزيد ←',
    interior: 'الجلسة الداخلية',
    ourCoffee: 'القهوة المختصة',
    ourPâtisserie: 'مخبوزات وفطائر',
    whyTitle: 'لماذا تختار هابي سبيس؟',
    reasons: [
      { text: 'موسيقى الجاز الصباحية لبداية يوم هادئة ولطيفة', icon: 'music' },
      { text: 'حلويات ومخبوزات مصنوعة بأعلى المعايير الفرنسية', icon: 'cake' },
      { text: 'قهوة مختصة مستوردة من مزارع عادلة ومستدامة', icon: 'coffee' },
      { text: 'مبنى تاريخي ذو طابع كولونيالي عريق ومحافظ عليه بالكامل', icon: 'landmark' },
      { text: 'خدمة دافئة، مبتسمة وشديدة الحرص على راحتكم', icon: 'heart' }
    ],
    comeVisitUs: 'تفضل بزيارتنا وتذوق الهدوء',
    openingHours: 'مفتوح يومياً : من 08:00 صباحاً حتى 22:00 مساءً',
    phoneNumber: '+213 (0) 21 00 00 00',
    bookingBtn: 'احجز طاولة الآن',
    mapTitle: 'الخريطة التفاعلية',
    exploreAlgiers: 'اكتشف قلب الجزائر العاصمة',
    allRightsReserved: 'الهدوء والمتعة في كل رشفة.',
    backToHome: '← الرئيسية',
    categories: {
      cafes: 'القهوة والشاي',
      boissons: 'المشروبات الباردة',
      patisseries: 'الحلويات والمخبوزات',
      salades: 'السلطات والمأكولات الخفيفة'
    },
    filterAll: 'جميع الأطباق',
    searchPlaceholder: 'ابحث عن قهوة أو حلوى مخصصة...',
    priceDZD: 'دج',
    cartTitle: 'سلة الطلبات الخاصة بك',
    cartEmpty: 'السلة فارغة حالياً. لا تتردد في إضافة بعض مختاراتنا الشهية.',
    addToCart: 'إضافة إلى السلة',
    customize: 'تخصيص كوبك ومشروبك',
    milkOption: 'نوع الحليب المفضل',
    sweetnessOption: 'درجة الحلاوة والتحلية',
    extraShotOption: 'إضافة جرعة إسبريسو (+100 دج)',
    notesPlaceholder: 'أي ملاحظات خاصة أخرى؟ تفضل بكتابتها هنا...',
    totalPrice: 'الإجمالي الكلي',
    total: 'المجموع الكلي',
    orderNow: 'تأكيد وإرسال الطلب',
    bookingTitle: 'احجز طاولة مسبقاً',
    fullName: 'الاسم الكامل',
    phoneNumberLabel: 'رقم الهاتف',
    emailLabel: 'البريد الإلكتروني (اختياري)',
    guestsNumber: 'عدد الحضور',
    bookingDate: 'التاريخ المطلوب',
    bookingTime: 'الوقت المحدد للتواجد',
    seatingArea: 'المنطقة والجلسة المفضلة',
    seatingOptions: {
      salle_principale: 'القاعة الرئيسية (أجواء كلاسيكية حية)',
      jazz_corner: 'ركن الجاز (بجانب العازفين)',
      window_view: 'إطلالة النافذة (مباشرة على شارع ديدوش مراد)',
      terrace: 'الشرفة الخارجية البسيطة للهواء الطلق'
    },
    specialRequests: 'ملاحظات أو طلبات خاصة بالحجز',
    confirmBooking: 'تأكيد الحجز الآن',
    bookingSuccess: 'ألف مبروك! تم تسجيل طلب الحجز الخاص بك بنجاح.',
    bookingUnderReview: 'سيقوم فريق الضيافة لدينا بالاتصال بك قريباً عبر الهاتف لتثبيت حجز طاولة.',
    cartSuccess: 'تم إرسال طلبك مباشرة لقسم الخدمة والتحضير!',
    cartTableNum: 'رقم الطاولة والموقع',
    myBookings: 'جداول الحجز الخاصة بي',
    noReservations: 'العثور على أي حجوزات مسبقة في جلستك الحالية.',
    optionsLabelWhole: 'حليب كامل الدسم كلاسيكي',
    optionsLabelOat: 'حليب الشوفان النباتي (+80 دج)',
    optionsLabelAlmond: 'حليب اللوز اللذيذ (+80 دج)',
    sweetnessNormal: 'حلاوة طبيعية كاملة',
    sweetnessLess: 'حلاوة قليلة وخفيفة',
    sweetnessNone: 'بدون أي سكر مضاف',
    allPricesExplanation: 'جميع أسعارنا معلنة بالدينار الجزائري وتتضمن الضرائب والخدمة.',
    servingTypeTable: 'خدمة عند الطاولة',
    servingTypeTakeaway: 'طلب سفري / خارجي',
    tablePlaceholder: 'مثال: طاولة رقم 4',
    servingTypeSelect: 'طريقة اختيار الخدمة',
    viewMyBookings: 'الحجوزات النشطة لدي',
    close: 'إغلاق',
    jazzLiveAt: 'عروض الجاز الحية والساكسفون تبدأ كل يوم في تمام السابعة مساءً',
    cancel: 'إلغاء الحجز',
    confirmedStatus: 'مؤكد ومحفوظ',
    orderHistory: 'الطلبات المسجلة',
    orderEmpty: 'لا توجد أي طلبات نشطة في الوقت الحالي.',
    orderPlaced: 'طلب رقم'
  }
};
